# Generated by Django 3.0.6 on 2020-05-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesEntry', '0007_auto_20200515_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemonade_name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('saleEntry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='salesEntry.SalesEntry')),
            ],
        ),
    ]
