# Generated by Django 3.0.6 on 2020-05-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkOrder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkorder',
            name='saleEntry',
        ),
        migrations.AddField(
            model_name='drinkorder',
            name='saleEntry_id',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
