# Generated by Django 3.0.6 on 2020-05-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkOrder', '0002_auto_20200515_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='saleEntry_id',
            field=models.IntegerField(default=9999),
        ),
    ]
