# Generated by Django 3.0.6 on 2020-05-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesEntry', '0011_auto_20200515_2342'),
        ('drinkOrder', '0004_auto_20200515_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='saleEntry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesEntry.SalesEntry'),
        ),
    ]
