# Generated by Django 3.0.6 on 2020-05-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkOrder', '0005_auto_20200515_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkorder',
            old_name='saleEntry_id',
            new_name='saleEntry',
        ),
    ]
