# Generated by Django 3.0.6 on 2020-05-17 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemonade', '0001_initial'),
        ('drinkOrder', '0006_auto_20200515_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='lemonade_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemonade.Lemonade'),
        ),
        migrations.AlterField(
            model_name='drinkorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
