# Generated by Django 3.0.6 on 2020-05-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemonade', '0001_initial'),
        ('drinkOrder', '0009_drinkorder_lemonade_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkorder',
            name='lemonade_name_id',
        ),
        migrations.AlterField(
            model_name='drinkorder',
            name='lemonade_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemonade.Lemonade'),
        ),
    ]
