# Generated by Django 3.0.6 on 2020-05-17 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesEntry', '0011_auto_20200515_2342'),
        ('drinkOrder', '0011_auto_20200517_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='lemonade_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='drinkorder',
            name='saleEntry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesEntry.SalesEntry'),
        ),
    ]
