# Generated by Django 3.0.6 on 2020-05-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesEntry', '0011_auto_20200515_2342'),
        ('lemonade', '0001_initial'),
        ('drinkOrder', '0012_auto_20200517_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='lemonade_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemonade_name', to='lemonade.Lemonade'),
        ),
        migrations.AlterField(
            model_name='drinkorder',
            name='saleEntry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleEntry', to='salesEntry.SalesEntry'),
        ),
    ]
