# Generated by Django 3.0.6 on 2020-05-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkOrder', '0013_auto_20200517_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkorder',
            name='price_per_drink',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
