# Generated by Django 3.0.6 on 2020-05-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkOrder', '0015_auto_20200518_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkorder',
            name='price_per_drink',
        ),
    ]
