# Generated by Django 3.0.6 on 2020-05-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkOrder', '0017_drinkorder_price_per_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkorder',
            name='price_per_drink',
        ),
    ]
