# Generated by Django 3.0.6 on 2020-05-18 08:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkOrder', '0018_remove_drinkorder_price_per_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkorder',
            name='price_per_drink',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=10),
        ),
    ]
