# Generated by Django 3.0.6 on 2020-05-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkOrder', '0021_remove_drinkorder_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkorder',
            name='price_per_drink',
        ),
    ]
