# Generated by Django 3.0.6 on 2020-05-20 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemonade', '0001_initial'),
        ('drinkOrder', '0022_remove_drinkorder_price_per_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='lemonade_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemonade_name', to='lemonade.Lemonade'),
        ),
    ]
