# Generated by Django 3.0.6 on 2020-05-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesentry',
            name='date',
            field=models.DateField(),
        ),
    ]
