# Generated by Django 3.0.6 on 2020-05-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesEntry', '0005_auto_20200514_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesentry',
            old_name='numOfCups',
            new_name='quantity',
        ),
    ]
