# Generated by Django 3.0.6 on 2020-05-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesEntry', '0006_auto_20200515_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesentry',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='salesentry',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='staffName',
            field=models.CharField(max_length=40),
        ),
    ]
