# Generated by Django 3.0.6 on 2020-05-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesEntry', '0007_auto_20200515_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesentry',
            name='staffID',
            field=models.IntegerField(null=True),
        ),
    ]
