# Generated by Django 3.0.6 on 2020-05-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesEntry', '0008_salesentry_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesentry',
            name='staffName',
            field=models.CharField(choices=[(1, 'Jeff Terry'), (3, 'John Rice'), (4, 'Larry Long'), (2, 'Thomas Black')], max_length=40),
        ),
    ]
