# Generated by Django 3.0.6 on 2020-05-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesEntry', '0010_auto_20200515_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesentry',
            name='staffName',
            field=models.CharField(max_length=40),
        ),
    ]
