# Generated by Django 3.0.6 on 2020-05-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemonade', '0001_initial'),
        ('salesEntry', '0011_auto_20200515_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lemonade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemonade', to='lemonade.Lemonade')),
                ('saleEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleEntry', to='salesEntry.SalesEntry')),
            ],
        ),
    ]
